services:
  # 1. Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: supportflow-prod-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: supportflow
      TZ: America/Caracas
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d supportflow"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  # 2. pgAdmin - Visor de tablas
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: supportflow-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      db:
        condition: service_healthy
    restart: always

  # 3. Corredor de migraciones automático de Prisma (se apaga una vez finalizado)
  migration:
    build:
      context: .
      target: builder
    container_name: supportflow-prod-migration
    command: npx prisma migrate deploy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres_password@db:5432/supportflow?schema=public
      - TZ=America/Caracas
    depends_on:
      db:
        condition: service_healthy

  # 4. Aplicación web de Next.js
  web:
    build:
      context: .
      target: runner
    container_name: supportflow-prod-web
    ports:
      - "80:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres_password@db:5432/supportflow?schema=public
      - NEXTAUTH_SECRET=supportflow-manager-secure-key-32-chars-long-or-more
      - NEXTAUTH_URL=http://10.10.30.53
      - TZ=America/Caracas
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    restart: always

volumes:
  pgdata:
